#!/usr/bin/env python3
from __future__ import annotations

import hashlib
import json
import re
import sys
import urllib.request
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
STITCH_ROOT = ROOT / "stitch_roadmitere"
ASSET_DIR = ROOT / "assets" / "stitch"
ASSET_MAP_PATH = ROOT / "src" / "assets-map.ts"
URL_PATTERN = re.compile(r'https://lh3\.googleusercontent\.com/[^\s"\')>]+')


def collect_remote_urls() -> list[str]:
    urls: set[str] = set()
    html_paths = sorted(STITCH_ROOT.rglob("code.html"), key=lambda path: path.as_posix())

    for html_path in html_paths:
        html_text = html_path.read_text(encoding="utf-8")
        for url in URL_PATTERN.findall(html_text):
            urls.add(url)

    return sorted(urls)


def detect_extension(data: bytes, content_type: str) -> str:
    normalized = content_type.lower().split(";")[0].strip()
    if normalized == "image/jpeg":
        return "jpg"
    if normalized == "image/png":
        return "png"
    if normalized == "image/webp":
        return "webp"
    if normalized == "image/gif":
        return "gif"
    if normalized == "image/svg+xml":
        return "svg"

    if data.startswith(b"\x89PNG\r\n\x1a\n"):
        return "png"
    if data[:3] == b"\xff\xd8\xff":
        return "jpg"
    if data[:4] == b"RIFF" and data[8:12] == b"WEBP":
        return "webp"
    if data.startswith(b"GIF87a") or data.startswith(b"GIF89a"):
        return "gif"
    if data.lstrip().startswith(b"<svg"):
        return "svg"
    return "bin"


def download_asset(url: str) -> tuple[bytes, str]:
    request = urllib.request.Request(
        url,
        headers={
            "User-Agent": (
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                "AppleWebKit/537.36 (KHTML, like Gecko) "
                "Chrome/131.0.0.0 Safari/537.36"
            )
        },
    )
    with urllib.request.urlopen(request, timeout=45) as response:
        data = response.read()
        content_type = response.headers.get_content_type()
    extension = detect_extension(data, content_type)
    return data, extension


def url_hash(url: str) -> str:
    return hashlib.sha256(url.encode("utf-8")).hexdigest()[:20]


def ensure_asset(url: str) -> Path:
    digest = url_hash(url)
    existing_files = sorted(ASSET_DIR.glob(f"lh3_{digest}.*"), key=lambda path: path.name)
    if existing_files:
        return existing_files[0]

    data, extension = download_asset(url)
    target = ASSET_DIR / f"lh3_{digest}.{extension}"
    target.write_bytes(data)
    return target


def write_asset_map(entries: list[tuple[str, Path]]) -> None:
    lines: list[str] = [
        "/* Auto-generated by scripts/download_remote_assets.py. Do not edit manually. */",
        'import type { ImageSourcePropType } from "react-native";',
        "",
        "export const stitchAssetMap: Record<string, ImageSourcePropType> = {",
    ]

    for url, asset_path in entries:
        serialized_url = json.dumps(url, ensure_ascii=False)
        lines.append(f'  {serialized_url}: require("../assets/stitch/{asset_path.name}"),')

    lines.extend(
        [
            "};",
            "",
            "export function resolveStitchAsset(url?: string | null): ImageSourcePropType | undefined {",
            "  if (!url) {",
            "    return undefined;",
            "  }",
            "  return stitchAssetMap[url];",
            "}",
            "",
        ]
    )

    ASSET_MAP_PATH.parent.mkdir(parents=True, exist_ok=True)
    ASSET_MAP_PATH.write_text("\n".join(lines), encoding="utf-8")


def remove_stale_assets(required_assets: set[str]) -> None:
    for asset_path in sorted(ASSET_DIR.glob("lh3_*"), key=lambda path: path.name):
        if asset_path.name not in required_assets:
            asset_path.unlink()


def main() -> int:
    if not STITCH_ROOT.exists():
        print(f"Missing stitch root: {STITCH_ROOT}", file=sys.stderr)
        return 1

    ASSET_DIR.mkdir(parents=True, exist_ok=True)

    urls = collect_remote_urls()
    if not urls:
        print("No remote lh3 assets found.")
        write_asset_map([])
        return 0

    entries: list[tuple[str, Path]] = []
    for url in urls:
        asset_path = ensure_asset(url)
        entries.append((url, asset_path))

    required_assets = {asset_path.name for _, asset_path in entries}
    remove_stale_assets(required_assets)
    write_asset_map(entries)

    print(f"Remote URLs discovered: {len(urls)}")
    print(f"Assets available locally: {len(required_assets)}")
    print(f"Generated asset map: {ASSET_MAP_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
