/* Auto-generated by scripts/download_remote_assets.py. Do not edit manually. */
import type { ImageSourcePropType } from "react-native";

export const stitchAssetMap: Record<string, ImageSourcePropType> = {
  "https://lh3.googleusercontent.com/aida-public/AB6AXuAz3OkBv3tPs2WMWjJdPpp0uiljhSjtd-WPJ70EsGOBP49i87ePDb_fJT7c1Oe_dcqkqLHNQhWrikv6SCvj_9mpbagp2TUt1EYbckONUBGFzlbl03Hv3qP1Mtp-kFvBYo4TdMdbXzBKEs9AufzcZN8-fqn_jAnvYMw8WtiIIV1onf-V_JYDiOGZs3f9m6StF8Du5c78zbc7F682fO-39WvfjN4M3sUn32fuDreHKlhJH2VGd71hAPJ3gAFuVSSqxe3pfJvsMdvPOmk": require("../assets/stitch/lh3_56a1639405e6b45a8f72.png"),
  "https://lh3.googleusercontent.com/aida-public/AB6AXuCIJxtOagqPgO5yVx98F1sbiXDb98ug1IpAkaa4XHL1nnx3VcFUytiHKGCGX3W2skFXleg3w0nLrl2jBXTb-5ihVwZw3y_Gnws5gz_dWcn0urk_Ei0i1VZJ8wC1hSvBQSu77N6s6TqEUBqE2zZx91kTS1yKn1Mi9tVBiTKaGeTORojYY_wfObZoUv9Z2DhtP7uHh8OjnuMQLDY_5T-65BBiQjElSSGDqlkPJ7J-L5a98-kMMSUKbuHZ6RY8c_jLOU_-9qVqJeSws0U": require("../assets/stitch/lh3_7c5fa2410628862e97b8.png"),
  "https://lh3.googleusercontent.com/aida-public/AB6AXuChT7bqptPwZh6KORlWxs-SNAJzmknkWUWfpwC1frzQ4NqiaWSFhnN5IuSflKyPPc_XmAAxMCPnpcozt747tAMclPg8z4esgKgDFNXfXv1z8lgaVB380XcqwehFwMUFWdz_V9qgn5vyLs12ETDt4ZrRABuyZ2XAGVXMfrpb8u35W8VFYK6x_u0D2u51yX4CJHcCyhA7OAOO4sDbDedNwzX9KkhtrRbB0lWMd1taJCNbnqPmtoADmGEMR5jCYojEB-rgeNyCh_5snwY": require("../assets/stitch/lh3_63fbdcd18103d0dbe90d.png"),
  "https://lh3.googleusercontent.com/aida-public/AB6AXuD-wem7QdNnnUUGHac-qC6YYg6sXl5278E-FfUxddyWMhMXElGi0QO79zU1-ajNaghwCeSq6MDZ-GOu0YShjFz4kUbBoRb3vxlrFpnAmqdItGU-PPUztVQaDBRw_mOF06lsQF5Ot0fVixWeA8QlZJCfIDhHN87OxihXSX3fGXjIIS247_PnUs_HK29o3EY9QwWbMHZEu1rrewosBW4CTs8Wzc3pYkJK5FNrAYagQJfA-G1ISIIUvpgbkm2RgdmbZ3bPGsoka6ssQbk": require("../assets/stitch/lh3_91abb466ee18bd68dc0e.png"),
  "https://lh3.googleusercontent.com/aida-public/AB6AXuDii46KrLTCRA2N5ta9PX9NNHgtz7GnKvhVgW-0biKkI3zq6GMKBr-DIH-1XBARzgFTMFmc2g5TocxcaCv_YHyBAwaA4Mtp9fcLVLBQJms8TUGrpLO5XlDbhlf-ayE744DFlUkiV4mYWRUgyT_RTiYpVfzRaSzDG724svLmjbdgRO6RF3QdMb_GHgbRSWLEW-re-Ct19I0fKqa2WbPtCTTpllwGtK-FaWxHKG9mWMUm0gsXGKCOe7eI0LGcLLcmJbPVYsulldX4YXk": require("../assets/stitch/lh3_c1b5cdd0687d38f69e9a.png"),
};

export function resolveStitchAsset(url?: string | null): ImageSourcePropType | undefined {
  if (!url) {
    return undefined;
  }
  return stitchAssetMap[url];
}
